### ISSUE TITLE
Errors in admixture-wrapper.py and cross-validation files empty

### ISSUE THREAD

**Issue by quinn-ca** [dportik/admixture-wrapper#1]
Hello,

I'm using this wrapper to run many iterations of admixture. I got seemingly valid results but noticed that the cross-validation files were empty. I then checked the error log and came across several errors (below). I don't see 'prune' in the code at all, so I'm not sure why I'm getting the value error. I'm new to bioinformatics and am not sure where to begin troubleshooting, so I'd appreciate any guidance you can offer. Thanks for making this useful wrapper!

```
Traceback (most recent call last):
  File "/mnt/data/qcarvey/stacks_workflow/07-filtered_vcfs/allsamples_defaultbwa_noSamFlags/softclipped10_populationsmaf05/iterativefiltering_autosomal_only/admixture/admixture-wrapper.py", line 204, in <module>
    main()
  File "/mnt/data/qcarvey/stacks_workflow/07-filtered_vcfs/allsamples_defaultbwa_noSamFlags/softclipped10_populationsmaf05/iterativefiltering_autosomal_only/admixture/admixture-wrapper.py", line 193, in main
    summarize_outputs(outdir, args.indir, args.kmin, args.kmax, p.split('.ped')[0])
  File "/mnt/data/qcarvey/stacks_workflow/07-filtered_vcfs/allsamples_defaultbwa_noSamFlags/softclipped10_populationsmaf05/iterativefiltering_autosomal_only/admixture/admixture-wrapper.py", line 151, in summarize_outp$
    kouts = sorted([f for f in outs if int(f.split('.')[1]) == i])
  File "/mnt/data/qcarvey/stacks_workflow/07-filtered_vcfs/allsamples_defaultbwa_noSamFlags/softclipped10_populationsmaf05/iterativefiltering_autosomal_only/admixture/admixture-wrapper.py", line 151, in <listcomp>
    kouts = sorted([f for f in outs if int(f.split('.')[1]) == i])
ValueError: invalid literal for int() with base 10: 'prune'
```

**Comment by dportik** [comment]
Hello @quinn-ca,
I would try running the script with the example data provided. If those example data do not produce any errors, then there may be something off with your input files. Try that first and we can go from there.
